#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
	state="$(pgrep -f "/usr/bin/pushbot/pushbot")"
	[ -n "$state" ] && return 0
	/usr/bin/pushbot/pushbot >/dev/null 2>&1 &
	echo "pushbot is starting now ..."
}

stop() {
	state="$(pgrep -f "/usr/bin/pushbot/pushbot")"
	[ -n "$state" ] && kill -9 $state 2>/dev/null
	echo "pushbot exit ..."
}

restart(){
	stop
	sleep 1
	start
	echo "restarted."
}
